### ISSUE TITLE
Mark all tracks at once?

### ISSUE THREAD

**Issue by commanderclif** [davidjb/itunes-change-play-count#1]
Thank you for the script! Works perfectly and just used it to mark a number of tracks. Curious if an "apply to all" feature could be added. So if I selected multiple tracks, instead of going through one by one, I could enter the new play count hit the apply all button and it would mark all the same. Thank you for considering.

**Comment by davidjb** [comment]
Hey @commanderclif, thanks for the suggestion!  Definitely helpful if clearing counts en masse or setting an album all at once.

I've implemented an "Apply to All" button that applies the given count to the selected tracks. Give it a try. It prompts for confirmation to avoid mistakes and it also allows you to select a bunch of tracks, set several individual counts and then clicking "Apply to All" will only apply to the remaining subset so you don't lose your manually-inputted counts.

**Comment by commanderclif** [comment]
Awesome! I've downloaded and I'll give it a try and let you know. Thanks for incorporating the suggestion!

**Comment by commanderclif** [comment]
The script works perfectly for multiple tracks! Only one problem. The track counts don't stick. I came across that there is some bug with iTunes Match or iTunes Cloud Library, which I have both, that blocks these script added counts from....well....counting. Freaking sucks. Existed as least as far back as 2016....
https://dougscripts.com/itunes/2016/04/play-counts-bug/

**Comment by davidjb** [comment]
Sorry to hear that - that's an unfortunate bug and given the age of that report, the odds of it being resolved don't appear great.  Perhaps try reaching out to Apple as well and adding your voice to the concerns.

My library is local so I don't see this happening but if the values take time to get overwritten, I wonder if you could hack a solution by changing a track's count, then playing/finishing a track such that iTunes itself saves the new value. Not pretty, but might work.

**Comment by commanderclif** [comment]
That is correct, if I let the Music app play the last few seconds of the track then it save the value. Noticed a bug in iOS music in that I can find tracks that when played on fully on an iOS device they don't sync the play through to mac OS app. I have a playlist where all the tracks in it have like 35 plays each and then a couple in there with zero. So yeah, a couple things to bring up with Apple!

**Comment by davidjb** [comment]
Hmm, that might be a workaround that could be implemented then in AppleScript - change the play count, play the track, skip to just before the end, wait for it to save and repeat. If there was a way to detect if iTunes Match or iTunes Cloud Library were enabled, this could be written into the existing AppleScript. Or, if not, a separate script created with this different implementation. PRs are very welcome 👍
